### PR TITLE
Configure cluster for jupyt

### PR DESCRIPTION
**Pull request by chizhonkova**
Issue: https://github.com/ytsaurus/yt-k8s-operator/issues/145.

### CODE REVIEW

**Review by l0kix2 — APPROVED** [review]

**Comment by Krock21** [comment]
Could you please also add ACO namespace creation?
//sys/access_control_object_namespace/jupyt

**Comment by chizhonkova** [comment]
> Could you please also add ACO namespace creation?
> //sys/access_control_object_namespace/jupyt

This namespace is created by the init script https://github.com/ytsaurus/ytsaurus/blob/main/yt/chyt/controller/internal/app/init_cluster.go#L112.

**Comment by Krock21** [comment]
Doesn't it create only "chyt" namespace?
https://github.com/ytsaurus/ytsaurus/blob/main/yt/chyt/controller/internal/chyt/cluster_initializer.go#L164

Because I saw in strawberry controller logs errors about missing jupyt namespace and had to create it manually

**Comment by chizhonkova** [comment]
You're right, I'll also add some code to the init script in another pr to ytsaurus.

**Comment by Krock21** [comment]
Thank you!

**Pull request merged**
